name: CI Pipeline    # Name of your workflow

on:
  push:
    branches:
      - main        # Trigger this workflow on push events to the main branch
  pull_request:
    branches:
      - main        # Trigger this workflow on pull requests to the main branch

jobs:
  build:
    runs-on:  windows-latest    # Specifies the operating system environment for the job

    steps:
      - name: Checkout code    # Checkout the repository code
        uses: actions/checkout@v2

      - name: Set up Node.js    # Set up Node.js environment (example)
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies    # Install dependencies
        run: npm install

      - name: Build application    # Build your application (example)
        run: npm run build

      - name: Run tests    # Run tests (example)
        run: npm test
